### ISSUE TITLE
Datenbankklassen

### ISSUE THREAD

**Issue by Dominik-O22** [zocke1r/Warenwirtschaft#1]
- [x] Adresse  
- [x] Status
- [x] Ausgangssrecchnung
- [x] AusgangsrechnungPosition
- [x] Bestellung
- [x] BestellungPositionPosition
- [x] Groesse
- [x] kategorie
- [x] Lieferant
- [x] Benutzer

**Comment by lamyty** [comment]
Hab Position gelöscht. Exisitierte nicht im DBM.
